name: BUG REPORT
description: Looks like you've encountered some bugs, and we're very sorry!
labels: ["BUG"  ]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "Check the item"
    description: "Please check each of the following items and check the box to confirm."
    options:
    - label: "I have read it carefully
    link: "[issue_library_specification](https://moystudio.github.io/issue_library_specification.io/)"
    and are willing to abide by the rules therein"
    - label: "I confirm that no one else in the Issues list has raised the same or similar issue as this one"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: The problem you're experiencing
    placeholder: "-(Please answer here)-"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: What do you expect to happen if you do that?
    placeholder: "-(Please answer here)-"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: HOW DO I REPRODUCE THIS BUG?
    placeholder: "-(Please answer here)-"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: What could be causing the problem
    placeholder: "-(If you don't know, please fill in "None")-"
- type: textarea
  id: "yml-6"
  attributes:
    label: System environment
    placeholder: "eg：Windows 7、Windows 11..."
  validations:
    required: true
- type: textarea
  id: "yml-7"
  attributes:
    label: THE LAUNCHER VERSION THAT ENCOUNTERED THE BUG
    placeholder: "eg：Alpha 0.0.1...
    "
  validations:
    required: true
- type: textarea
  id: "yml-8"
  attributes:
    label: remark
    placeholder: "-(Please answer here, if not, please fill in "None")-"
